/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EnrollRequest } from '../../models/enroll-request';
import { EnrollResponse } from '../../models/enroll-response';

export interface EnrollHost$Params {
      body: EnrollRequest
}

export function enrollHost(http: HttpClient, rootUrl: string, params: EnrollHost$Params, context?: HttpContext): Observable<StrictHttpResponse<EnrollResponse>> {
  const rb = new RequestBuilder(rootUrl, enrollHost.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EnrollResponse>;
    })
  );
}

enrollHost.PATH = '/v1/enroll';
