/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Certificate } from '../../models/certificate';

export interface ListCertificates$Params {
  limit?: number;
}

export function listCertificates(http: HttpClient, rootUrl: string, params?: ListCertificates$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Certificate>>> {
  const rb = new RequestBuilder(rootUrl, listCertificates.PATH, 'get');
  if (params) {
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Certificate>>;
    })
  );
}

listCertificates.PATH = '/v1/admin/certificates';
