/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Host } from '../../models/host';

export interface ListHosts$Params {
}

export function listHosts(http: HttpClient, rootUrl: string, params?: ListHosts$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Host>>> {
  const rb = new RequestBuilder(rootUrl, listHosts.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Host>>;
    })
  );
}

listHosts.PATH = '/v1/admin/hosts';
