/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ServiceAccount } from '../../models/service-account';

export interface ListServiceAccounts$Params {
}

export function listServiceAccounts(http: HttpClient, rootUrl: string, params?: ListServiceAccounts$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ServiceAccount>>> {
  const rb = new RequestBuilder(rootUrl, listServiceAccounts.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ServiceAccount>>;
    })
  );
}

listServiceAccounts.PATH = '/v1/admin/service-accounts';
