/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ServiceAccount } from '../../models/service-account';

export interface UpdateServiceAccount$Params {
  id: string;
      body: {
'active': boolean;
}
}

export function updateServiceAccount(http: HttpClient, rootUrl: string, params: UpdateServiceAccount$Params, context?: HttpContext): Observable<StrictHttpResponse<ServiceAccount>> {
  const rb = new RequestBuilder(rootUrl, updateServiceAccount.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ServiceAccount>;
    })
  );
}

updateServiceAccount.PATH = '/v1/admin/service-accounts/{id}';
