/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AuthSession } from '../../models/auth-session';

export interface GetAuthMe$Params {
}

export function getAuthMe(http: HttpClient, rootUrl: string, params?: GetAuthMe$Params, context?: HttpContext): Observable<StrictHttpResponse<AuthSession>> {
  const rb = new RequestBuilder(rootUrl, getAuthMe.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AuthSession>;
    })
  );
}

getAuthMe.PATH = '/v1/auth/me';
