/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UiConfig } from '../../models/ui-config';

export interface GetUiConfig$Params {
}

export function getUiConfig(http: HttpClient, rootUrl: string, params?: GetUiConfig$Params, context?: HttpContext): Observable<StrictHttpResponse<UiConfig>> {
  const rb = new RequestBuilder(rootUrl, getUiConfig.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UiConfig>;
    })
  );
}

getUiConfig.PATH = '/v1/ui/config';
