/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApplyResult } from '../../models/apply-result';
import { GrantRequest } from '../../models/grant-request';

export interface ApplyGrants$Params {
      body: {
'grants'?: Array<GrantRequest>;
}
}

export function applyGrants(http: HttpClient, rootUrl: string, params: ApplyGrants$Params, context?: HttpContext): Observable<StrictHttpResponse<ApplyResult>> {
  const rb = new RequestBuilder(rootUrl, applyGrants.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApplyResult>;
    })
  );
}

applyGrants.PATH = '/v1/admin/grants/apply';
