/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Grant } from '../../models/grant';
import { GrantRequest } from '../../models/grant-request';

export interface CreateGrant$Params {
      body: GrantRequest
}

export function createGrant(http: HttpClient, rootUrl: string, params: CreateGrant$Params, context?: HttpContext): Observable<StrictHttpResponse<Grant>> {
  const rb = new RequestBuilder(rootUrl, createGrant.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Grant>;
    })
  );
}

createGrant.PATH = '/v1/admin/grants';
