/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Grant } from '../../models/grant';

export interface GetGrant$Params {
  id: string;
}

export function getGrant(http: HttpClient, rootUrl: string, params: GetGrant$Params, context?: HttpContext): Observable<StrictHttpResponse<Grant>> {
  const rb = new RequestBuilder(rootUrl, getGrant.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Grant>;
    })
  );
}

getGrant.PATH = '/v1/admin/grants/{id}';
