/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Grant } from '../../models/grant';

export interface ListGrants$Params {
}

export function listGrants(http: HttpClient, rootUrl: string, params?: ListGrants$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Grant>>> {
  const rb = new RequestBuilder(rootUrl, listGrants.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Grant>>;
    })
  );
}

listGrants.PATH = '/v1/admin/grants';
