/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CiGrant } from '../../models/ci-grant';
import { CiGrantRequest } from '../../models/ci-grant-request';

export interface CreateCiGrant$Params {
      body: CiGrantRequest
}

export function createCiGrant(http: HttpClient, rootUrl: string, params: CreateCiGrant$Params, context?: HttpContext): Observable<StrictHttpResponse<CiGrant>> {
  const rb = new RequestBuilder(rootUrl, createCiGrant.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CiGrant>;
    })
  );
}

createCiGrant.PATH = '/v1/admin/ci-grants';
