/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SignRequest } from '../../models/sign-request';
import { SignResponse } from '../../models/sign-response';

export interface SignCi$Params {
      body: SignRequest
}

export function signCi(http: HttpClient, rootUrl: string, params: SignCi$Params, context?: HttpContext): Observable<StrictHttpResponse<SignResponse>> {
  const rb = new RequestBuilder(rootUrl, signCi.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SignResponse>;
    })
  );
}

signCi.PATH = '/v1/sign/ci';
