/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AgentBinary } from '../models/agent-binary';
export interface AgentManifest {
  agents: Array<AgentBinary>;

  /**
   * Fehlende Rollout-Bedingungen
   */
  missing: Array<'binaries' | 'pin' | 'agent_public_url' | 'public_url'>;

  /**
   * Aktive SPKI-Pin-Quelle (leer ⇒ kein Pin)
   */
  pin_source: string;

  /**
   * false ⇒ Rollout-Endpunkte antworten mit 503
   */
  rollout_ready: boolean;
  version: string;
}
