/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AgentBinary } from '../models/agent-binary';
export interface AgentManifest {
  agents: Array<AgentBinary>;

  /**
   * Fehlende Rollout-Bedingungen
   */
  missing: Array<'binaries' | 'pin' | 'agent_public_url' | 'public_url'>;

  /**
   * Grobe Kategorie des letzten Pin-Fehlers (leer ⇒ keiner). Kein Volltext — der steht nur im Server-Log.
   */
  pin_error: '' | 'no_public_url' | 'chain_untrusted' | 'dial_failed' | 'cert_file_unreadable';

  /**
   * Aktive SPKI-Pin-Quelle (leer ⇒ kein Pin)
   */
  pin_source: string;

  /**
   * false ⇒ Rollout-Endpunkte antworten mit 503
   */
  rollout_ready: boolean;
  version: string;
}
