/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AgentBinary } from '../models/agent-binary';
export interface AgentManifest {
  agents: Array<AgentBinary>;

  /**
   * Missing rollout conditions. The *_https entries report a URL that is set but not https — http never passes the gate.
   */
  missing: Array<'binaries' | 'pin' | 'agent_public_url' | 'public_url' | 'agent_public_url_https' | 'public_url_https'>;

  /**
   * Coarse category of the last pin error (empty ⇒ none). No full text — that is only in the server log.
   */
  pin_error: '' | 'no_public_url' | 'chain_untrusted' | 'dial_failed' | 'cert_file_unreadable';

  /**
   * Active SPKI pin source (empty ⇒ no pin)
   */
  pin_source: string;

  /**
   * false ⇒ rollout endpoints respond with 503
   */
  rollout_ready: boolean;
  version: string;
}
