/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AgentBinary {
  arch: string;
  os: string;

  /**
   * Hex-SHA-256 (sha256sum-kompatibel)
   */
  sha256: string;
  size: number;
}
