/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuditEvent {
  actor: string;

  /**
   * z. B. cert.issued, grant.created/updated/deleted, host.enrolled, user.deactivated, service_account.updated
   */
  event_type: string;
  id: number;
  occurred_at: string;

  /**
   * Ereignis-Details als JSON
   */
  payload: {
};
}
