/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuditEvent } from '../models/audit-event';
export interface AuditList {
  events: Array<AuditEvent>;

  /**
   * Total count for the filter (for pagination)
   */
  total: number;
}
