/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuthSession {
  authenticated: boolean;
  roles?: Array<'admin' | 'auditor' | 'readonly'>;
  username?: string;
}
