/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Certificate {
  cert_type: 'user' | 'host';
  created_at: string;
  id: string;

  /**
   * Kontext der Ausstellung (SSO-Session, CI-Pipeline-Claims)
   */
  issuer_context?: {
};
  key_id: string;
  principals: Array<string>;
  serial: number;
  valid_after: string;
  valid_before: string;
}
