/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CiGrant {
  created_at: string;
  environment_pattern?: string;
  id: string;
  max_validity_seconds: number;
  principals: Array<string>;

  /**
   * GitLab-Projekt- oder Namespace-Pfad
   */
  project: string;
  protected_only: boolean;
  ref_pattern?: string;
  tag_selector: {
[key: string]: string;
};
  updated_at: string;
}
