/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CiGrantRequest {
  environment_pattern?: string;
  max_validity_seconds: number;
  principals: Array<string>;

  /**
   * Pflicht bei POST
   */
  project?: string;
  protected_only?: boolean;
  ref_pattern?: string;
  tag_selector?: {
[key: string]: string;
};
}
