/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ClientBinary {
  arch: string;
  os: string;

  /**
   * Hex SHA-256 (sha256sum-compatible)
   */
  sha256: string;
  size: number;
}
