/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ClientBinary } from '../models/client-binary';
export interface ClientManifest {
  clients: Array<ClientBinary>;

  /**
   * Missing client-install conditions. public_url_https reports a URL that is set but not https — http never passes the gate. The pin is deliberately not a condition (it is an opt-in, see the security model).
   */
  missing: Array<'binaries' | 'public_url' | 'public_url_https' | 'oidc_issuer' | 'oidc_client_id'>;

  /**
   * SPKI pin for the login-via-IP fallback, populated only from an operator-controlled source (static/file). Empty with an auto-derived (dial) pin: it rotates with the certificate and must never become a client's stored trust anchor.
   */
  pin: string;

  /**
   * Active SPKI pin source (static|file|dial; empty ⇒ none configured)
   */
  pin_source: string;

  /**
   * false ⇒ /v1/clients/{os}/{arch} and /client.sh respond with 503
   */
  ready: boolean;
  version: string;
}
