/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EnrollResponse {
  host_certificate: string;
  host_id: string;
  mtls_ca: string;
  mtls_certificate: string;
  user_ca_bundle: string;
  valid_before: string;
}
