/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EnrollTokenRequest {

  /**
   * empty ⇒ token not bound to a hostname
   */
  hostname?: string;

  /**
   * Only sets --session-audit in install_command; not stored on the token
   */
  session_audit?: boolean;
  tags?: {
[key: string]: string;
};
  ttl_seconds?: number;
}
