/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EnrollTokenResponse {
  expires_at: string;
  install_command: string;

  /**
   * Klartext
   */
  token: string;
}
