/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EnrollTokenRequest {

  /**
   * leer ⇒ Token nicht an einen Hostnamen gebunden
   */
  hostname?: string;

  /**
   * Setzt nur --session-audit im install_command; nicht am Token gespeichert
   */
  session_audit?: boolean;
  tags?: {
[key: string]: string;
};
  ttl_seconds?: number;
}
