/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EnrollRequest {
  hostname: string;

  /**
   * PEM-kodierter CSR für das mTLS-Client-Zertifikat
   */
  mtls_csr: string;
  ssh_public_key: string;
  tags?: {
[key: string]: string;
};
  token: string;
}
