/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GrantRequest {

  /**
   * Pflicht bei POST
   */
  group?: string;

  /**
   * leer ⇒ Issuer des Admin-Tokens
   */
  issuer?: string;
  max_validity_seconds: number;
  principals: Array<string>;
  sudo?: boolean;
  tag_selector?: {
[key: string]: string;
};
}
