/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Grant {
  created_at: string;

  /**
   * Gruppenname im IdP
   */
  group: string;
  id: string;
  issuer: string;
  max_validity_seconds: number;
  principals: Array<string>;
  sudo: boolean;
  tag_selector: {
[key: string]: string;
};
  updated_at: string;
}
