/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Host {

  /**
   * Latest valid_before among the host certificates
   */
  cert_valid_before?: string | null;
  created_at: string;
  enrolled_at?: string | null;
  id: string;

  /**
   * Agent's observed source IP at the last contact (no port). Egress address — behind NAT not necessarily the address sshd listens on.
   */
  last_seen_addr?: string | null;
  last_seen_at?: string | null;
  name: string;
  tags: {
[key: string]: string;
};
}
