/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Body of a rule write blocked by the provisioning gate; `code` is stable, `error` is the human-facing explanation naming the environment variable / chart value that owns the domain.
 */
export interface RulesWriteError {
  code: 'manual_rules_disabled' | 'rules_file_managed';
  error: string;
}
