/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ServiceAccount {

  /**
   * false acts as a kill switch per project
   */
  active: boolean;
  claim_matcher: {
[key: string]: string;
};
  created_at: string;
  id: string;
  issuer: string;
  kind: string;
  name: string;
  updated_at: string;
}
