/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SignRequest {

  /**
   * SSH public key in authorized_keys format
   */
  public_key: string;

  /**
   * Requested validity; capped by policy and grants
   */
  validity_seconds?: number;
}
