/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SignRequest {

  /**
   * SSH-Public-Key im authorized_keys-Format
   */
  public_key: string;

  /**
   * Gewünschte Laufzeit; wird durch Policy und Grants gedeckelt
   */
  validity_seconds?: number;
}
