/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SignResponse {
  certificate: string;
  key_id: string;
  principals: Array<string>;
  serial: number;
  valid_after: string;
  valid_before: string;
}
