/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UiConfig {
  admin_group: string;
  auditor_group: string;
  oidc_client_id: string;
  oidc_issuer: string;
  readonly_group: string;
}
