/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Public bootstrap configuration. The OIDC fields describe the clients' public OIDC client (consumed by the client-setup page and client.sh) — never the server's confidential login client.
 */
export interface UiConfig {
  admin_group: string;
  auditor_group: string;

  /**
   * Public OIDC client of the gssh CLIs (no client secret, GSSH_CLIENT_OIDC_CLIENT_ID); also the audience the server expects on bearer tokens.
   */
  oidc_client_id: string;
  oidc_issuer: string;
}
