/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface User {
  active: boolean;
  created_at: string;
  email: string;
  groups: Array<string>;
  id: string;
  issuer: string;
  subject: string;
  updated_at: string;
  username: string;
}
