/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClientManifest } from '../../models/client-manifest';

export interface GetClientManifest$Params {
}

export function getClientManifest(http: HttpClient, rootUrl: string, params?: GetClientManifest$Params, context?: HttpContext): Observable<StrictHttpResponse<ClientManifest>> {
  const rb = new RequestBuilder(rootUrl, getClientManifest.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ClientManifest>;
    })
  );
}

getClientManifest.PATH = '/v1/clients';
