/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EnrollTokenRequest } from '../../models/enroll-token-request';
import { EnrollTokenResponse } from '../../models/enroll-token-response';

export interface CreateEnrollToken$Params {
      body?: EnrollTokenRequest
}

export function createEnrollToken(http: HttpClient, rootUrl: string, params?: CreateEnrollToken$Params, context?: HttpContext): Observable<StrictHttpResponse<EnrollTokenResponse>> {
  const rb = new RequestBuilder(rootUrl, createEnrollToken.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<EnrollTokenResponse>;
    })
  );
}

createEnrollToken.PATH = '/v1/admin/enroll-tokens';
