/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AgentManifest } from '../../models/agent-manifest';

export interface GetAgentManifest$Params {
}

export function getAgentManifest(http: HttpClient, rootUrl: string, params?: GetAgentManifest$Params, context?: HttpContext): Observable<StrictHttpResponse<AgentManifest>> {
  const rb = new RequestBuilder(rootUrl, getAgentManifest.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AgentManifest>;
    })
  );
}

getAgentManifest.PATH = '/v1/agents';
