/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AuditEvent } from '../../models/audit-event';

export interface ExportAudit$Json$Params {
  format?: 'json' | 'csv';
  event_type?: string;
  actor?: string;
  q?: string;
  since?: string;
  until?: string;
}

export function exportAudit$Json(http: HttpClient, rootUrl: string, params?: ExportAudit$Json$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AuditEvent>>> {
  const rb = new RequestBuilder(rootUrl, exportAudit$Json.PATH, 'get');
  if (params) {
    rb.query('format', params.format, {});
    rb.query('event_type', params.event_type, {});
    rb.query('actor', params.actor, {});
    rb.query('q', params.q, {});
    rb.query('since', params.since, {});
    rb.query('until', params.until, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AuditEvent>>;
    })
  );
}

exportAudit$Json.PATH = '/v1/admin/audit/export';
