/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AuditList } from '../../models/audit-list';

export interface ListAudit$Params {
  event_type?: string;
  actor?: string;

/**
 * Teilstring über Actor und Payload
 */
  q?: string;
  since?: string;
  until?: string;
  limit?: number;
  offset?: number;
}

export function listAudit(http: HttpClient, rootUrl: string, params?: ListAudit$Params, context?: HttpContext): Observable<StrictHttpResponse<AuditList>> {
  const rb = new RequestBuilder(rootUrl, listAudit.PATH, 'get');
  if (params) {
    rb.query('event_type', params.event_type, {});
    rb.query('actor', params.actor, {});
    rb.query('q', params.q, {});
    rb.query('since', params.since, {});
    rb.query('until', params.until, {});
    rb.query('limit', params.limit, {});
    rb.query('offset', params.offset, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AuditList>;
    })
  );
}

listAudit.PATH = '/v1/admin/audit';
